/* Generated by modconv 2 */

const GeoLayout xander_geo[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xC8, 60),
    GEO_OPEN_NODE(),
        GEO_SCALE(0x00, 16384),
        GEO_OPEN_NODE(),
            GEO_ROTATE_WITH_DL(LAYER_OPAQUE, 0x4000, 0x0000, 0x4000, xander_dl_opaque),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END()
};
